#!/bin/bash

set -euo pipefail

echo "Checking if .proto files are in sync..."

# Create and clean temp dir
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Prepare temp output path
mkdir -p "$TEMP_DIR/pkg/api"

# Generate proto into TEMP_DIR using identical flags to Makefile
protoc --proto_path=./ \
	     --go_out="$TEMP_DIR/pkg" --go_opt=paths=source_relative \
       --go-grpc_out="$TEMP_DIR/pkg" --go-grpc_opt=paths=source_relative \
      proto/*.proto

# Compare with current pkg/proto
if ! diff -qr "$TEMP_DIR/pkg/proto" pkg/proto > /dev/null; then
  echo "Protobufs are out of sync. Please run: make proto"
  exit 1
fi

echo "Protobufs are in sync."
