// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: api/compute.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Filepath      string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Shard         int32                  `protobuf:"varint,3,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_api_compute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_api_compute_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *JobRequest) GetShard() int32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_api_compute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_api_compute_proto_rawDescGZIP(), []int{1}
}

func (x *JobResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *JobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_compute_proto protoreflect.FileDescriptor

const file_api_compute_proto_rawDesc = "" +
	"\n" +
	"\x11api/compute.proto\x12\x03api\"U\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\x05R\x05shard\"=\n" +
	"\vJobResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2@\n" +
	"\x0eComputeService\x12.\n" +
	"\tSubmitJob\x12\x0f.api.JobRequest\x1a\x10.api.JobResponseB&Z$github.com/UCLA-IRL/flint-go/pkg/apib\x06proto3"

var (
	file_api_compute_proto_rawDescOnce sync.Once
	file_api_compute_proto_rawDescData []byte
)

func file_api_compute_proto_rawDescGZIP() []byte {
	file_api_compute_proto_rawDescOnce.Do(func() {
		file_api_compute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_compute_proto_rawDesc), len(file_api_compute_proto_rawDesc)))
	})
	return file_api_compute_proto_rawDescData
}

var file_api_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_compute_proto_goTypes = []any{
	(*JobRequest)(nil),  // 0: api.JobRequest
	(*JobResponse)(nil), // 1: api.JobResponse
}
var file_api_compute_proto_depIdxs = []int32{
	0, // 0: api.ComputeService.SubmitJob:input_type -> api.JobRequest
	1, // 1: api.ComputeService.SubmitJob:output_type -> api.JobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_compute_proto_init() }
func file_api_compute_proto_init() {
	if File_api_compute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_compute_proto_rawDesc), len(file_api_compute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_compute_proto_goTypes,
		DependencyIndexes: file_api_compute_proto_depIdxs,
		MessageInfos:      file_api_compute_proto_msgTypes,
	}.Build()
	File_api_compute_proto = out.File
	file_api_compute_proto_goTypes = nil
	file_api_compute_proto_depIdxs = nil
}
