// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: proto/static.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StaticComputeService_Add_FullMethodName = "/api.StaticComputeService/Add"
)

// StaticComputeServiceClient is the client API for StaticComputeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaticComputeServiceClient interface {
	// Sends an add request to the NDN compute backend
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type staticComputeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStaticComputeServiceClient(cc grpc.ClientConnInterface) StaticComputeServiceClient {
	return &staticComputeServiceClient{cc}
}

func (c *staticComputeServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, StaticComputeService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaticComputeServiceServer is the server API for StaticComputeService service.
// All implementations must embed UnimplementedStaticComputeServiceServer
// for forward compatibility.
type StaticComputeServiceServer interface {
	// Sends an add request to the NDN compute backend
	Add(context.Context, *AddRequest) (*AddResponse, error)
	mustEmbedUnimplementedStaticComputeServiceServer()
}

// UnimplementedStaticComputeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStaticComputeServiceServer struct{}

func (UnimplementedStaticComputeServiceServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedStaticComputeServiceServer) mustEmbedUnimplementedStaticComputeServiceServer() {}
func (UnimplementedStaticComputeServiceServer) testEmbeddedByValue()                              {}

// UnsafeStaticComputeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaticComputeServiceServer will
// result in compilation errors.
type UnsafeStaticComputeServiceServer interface {
	mustEmbedUnimplementedStaticComputeServiceServer()
}

func RegisterStaticComputeServiceServer(s grpc.ServiceRegistrar, srv StaticComputeServiceServer) {
	// If the following call pancis, it indicates UnimplementedStaticComputeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StaticComputeService_ServiceDesc, srv)
}

func _StaticComputeService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticComputeServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticComputeService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticComputeServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StaticComputeService_ServiceDesc is the grpc.ServiceDesc for StaticComputeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaticComputeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.StaticComputeService",
	HandlerType: (*StaticComputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _StaticComputeService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/static.proto",
}
